policies:
  # The following policy is designed to work from GitHub action workflows.
  # This means that before running any Updatecli command, we need the two following environment variables set:
  # 
  #   GITHUB_TOKEN: Set to a personal access token
  #   GITHUB_ACTOR: Set to the username associated with the GITHUB_TOKEN
  # 
  # Instruction to retrieve your PAT is documented on https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
  - name: Handle docusaurus versioning
    policy: ghcr.io/olblak/rancherlabs-policies/docusaurus/versioning:0.1.0@sha256:6693eee54400675304b58e38df91681b4da0358a9ddb3266825ffb78ce9a9a24
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/fleet.yaml
  - name: Handle releasepost
    policy: ghcr.io/olblak/rancherlabs-policies/docusaurus/releasepost:0.4.1
    values:
      - updatecli/values.d/scm.yaml
      - updatecli/values.d/fleet.yaml
  - name: Handle Updatecli policies
    policy: ghcr.io/updatecli/policies/autodiscovery/updatecli:0.4.0@sha256:254367f5b1454fd6032b88b314450cd3b6d5e8d5b6c953eb242a6464105eb869
    values:
      - updatecli/values.d/scm-2.yaml
